### ISSUE TITLE
Cannot resolve dependency 

### ISSUE THREAD

**Issue by amanpreeto7** [ImaginativeShohag/Oops-No-Internet#1]
Failed to resolve: com.github.ImaginativeShohag:Oops-No-Internet:v1.1.5
Show in Project Structure dialog

Style Material design theme
min sdk 23
project is in androidx

**Comment by ImaginativeShohag** [comment]
Maybe you forgot to add the jitpack repository to your root `gradle.build` file.

Please add it to your root `build.gradle` at the end of repositories:

```
allprojects {
    repositories {
        // ...
        maven { url 'https://jitpack.io' }
    }
}
```

And try also try this, File > Invalidate Caches / Restart... > Invalidate and Restart

**Comment by amanpreeto7** [comment]
it is not working with classpath "com.android.tools.build:gradle:4.0.1"

**Comment by ImaginativeShohag** [comment]
In you root `gradle.build` file, add `maven { url 'https://jitpack.io' }` inside `allprojects > repositories` section. You don't need to remove anything from the existing file. Your full `gradle.build` file structure should look like this:

```gradle
buildscript {
        // other variables
    repositories {

        // other repositories

    }
    dependencies {
        
        // other dependencies

    }
}

allprojects {
    repositories {

        // other repositories

        maven { url "https://jitpack.io" } // < this line is for Oops No Internet library.
    }
}
```
