### ISSUE TITLE
ConnectionCallback is calling twice on startup

### ISSUE THREAD

**Issue by behnawwm** [ImaginativeShohag/Oops-No-Internet#13]
Why the `ConnectionCallback` is called twice on my fragment startup?
Is that a bug or is that with my project?
How can I make it to call only once on startup?

**Comment by ImaginativeShohag** [comment]
It's not a bug. It's normal. If you don't want multiple calls, you can use a flag variable to see if the callback has already been called once.

Example:
```kotlin
// Global variable
var hasConnection : Boolean = true

// ...

connectionCallback = object : ConnectionCallback {
    override fun hasActiveConnection(hasActiveConnection: Boolean) {
        if(hasActiveConnection != hasConnection) {
            hasConnection = hasActiveConnection

            // Do something here
        }
    }
}

```
