### ISSUE TITLE
get lifeCycle object

### ISSUE THREAD

**Issue by Dave181295** [ImaginativeShohag/Oops-No-Internet#5]
Thanks for your awesome library !
I'm trying to implement it in my` Application() `class  I have implemented `Application.ActivityLifecycleCallbacks` so it will trigger in each onCreate for all activities, but I can't get the lifecycle object.. I'm on Kotlin ..

**Comment by Dave181295** [comment]
_RESOLVED_
i casted the activity parameter into appCompatActivity

**Comment by abumoallim** [comment]
Can you write the code of how you did it?
